import express from 'express';
import passport from 'passport';
import { protect } from '../middleware/auth';
import * as ac from '../controllers/authController';
const router = express.Router();
router.post('/register', ac.register);
router.post('/login', ac.login);
router.post('/logout', ac.logout);
router.post('/forgot-password', ac.forgotPassword);
router.post('/reset-password/:token', ac.resetPassword);
router.get('/google', passport.authenticate('google', { scope: ['profile', 'email'] }));
router.get('/google/callback', passport.authenticate('google', { failureRedirect: '/login' }), ac.googleCallback);
router.get('/me', protect, ac.getMe);
router.put('/change-password', protect, ac.changePassword);
export default router;
