import express from 'express';
import { protect } from '../middleware/auth';
import * as tc from '../controllers/tournamentController';
const router = express.Router();
router.get('/', tc.getTournaments);
router.get('/my', protect, tc.getMyTournaments);
router.get('/:id', tc.getTournamentById);
router.get('/:id/points-table', tc.getPointsTable);
router.post('/', protect, tc.createTournament);
router.put('/:id', protect, tc.updateTournament);
router.delete('/:id', protect, tc.deleteTournament);
router.post('/:id/bracket', protect, tc.generateBracket);
router.post('/:id/start', protect, tc.startTournament);
export default router;
